# Análise de Desempenho do Palmeiras no Campeonato Brasileiro 2025

## 1. Definição do Problema de Negócio

### 1.1. Contexto

O Campeonato Brasileiro de Futebol é uma das ligas mais competitivas do mundo, e o desempenho de um clube ao longo da temporada é de grande interesse para torcedores, analistas esportivos e a própria gestão do time. A capacidade de analisar dados de partidas pode revelar padrões, pontos fortes e fracos, e auxiliar na tomada de decisões estratégicas.

Este projeto foca na análise do desempenho do Sociedade Esportiva Palmeiras no Campeonato Brasileiro de 2025, utilizando dados públicos de resultados de jogos. O objetivo é transformar esses dados brutos em *insights* claros sobre a performance do time.

### 1.2. Problema de Negócio

Para torcedores e a comissão técnica, entender o desempenho de um time vai além de apenas ver a tabela de classificação. Questões como:

- **Desempenho Geral:** Qual foi o balanço de vitórias, empates e derrotas do Palmeiras?
- **Performance em Casa vs. Fora:** O time joga melhor em casa ou como visitante? Há uma diferença significativa na pontuação ou no saldo de gols?
- **Eficiência Ofensiva e Defensiva:** Quantos gols o time marcou e sofreu? Qual a média de gols por partida?
- **Consistência ao Longo do Tempo:** Existem períodos (meses ou dias da semana) em que o desempenho é notavelmente melhor ou pior?

Responder a essas perguntas de forma estruturada e visual é fundamental para avaliar a campanha do time e identificar áreas para melhoria.

### 1.3. Objetivos do Projeto

O objetivo principal deste projeto é realizar uma Análise Exploratória de Dados (EDA) do desempenho do Palmeiras no Campeonato Brasileiro de 2025 para extrair *insights* relevantes.

Os objetivos específicos são:

- **Calcular Métricas de Desempenho:** Determinar o número total de vitórias, empates, derrotas e pontos conquistados pelo Palmeiras.
- **Analisar Gols:** Calcular o total de gols marcados (pró) e sofridos (contra), e o saldo de gols.
- **Comparar Local de Jogo:** Avaliar o desempenho do time em partidas jogadas em casa e fora de casa.
- **Identificar Tendências Temporais:** Analisar a performance do time por mês e por dia da semana para identificar padrões.
- **Identificar Vítimas e Carrascos:** Determinar quais times o Palmeiras mais venceu e mais perdeu.

### 1.4. Critérios de Sucesso

O projeto será considerado um sucesso ao entregar:

- Um *dataset* pré-processado com as informações de desempenho do Palmeiras.
- Métricas claras e concisas sobre o desempenho geral do time.
- Visualizações que comparem o desempenho em casa e fora, e ao longo do tempo.
- Identificação dos principais adversários (vítimas e carrascos).
- Conclusões baseadas em dados que respondam às perguntas de negócio iniciais.
- Dados prontos para importação em ferramentas de BI como o Power BI.

## 2. Importando Bibliotecas

In [165]:
import pandas as pd
import numpy as np

## 3. Carregando e Compreendendo os Dados

In [166]:
# Define nome do arquivo
nome_arquivo_csv = 'brasileirao_2025.csv'

In [167]:
# Carrega o dataset
df_brasileirao_2025 = pd.read_csv(nome_arquivo_csv)

### 3.1. Análise Estrutural do Dataset
Verificação das dimensões, primeiras e últimas linhas, tipos de dados e valores ausentes para uma compreensão inicial do dataset.

In [168]:
# shape
df_brasileirao_2025.shape

(380, 7)

In [169]:
# Primeiras linhas
df_brasileirao_2025.head()

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status
0,2025-03-29T21:30:00Z,1,São Paulo FC,SC Recife,0,0,FINISHED
1,2025-03-29T21:30:00Z,1,Cruzeiro EC,Mirassol FC,2,1,FINISHED
2,2025-03-29T21:30:00Z,1,Grêmio FBPA,CA Mineiro,2,1,FINISHED
3,2025-03-29T21:30:00Z,1,Fortaleza EC,Fluminense FC,2,0,FINISHED
4,2025-03-29T21:30:00Z,1,EC Juventude,EC Vitória,2,0,FINISHED

In [170]:
# Amostra dos dados
df_brasileirao_2025.sample(10)

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status
288,2025-10-25T20:30:00Z,30,Fluminense FC,SC Internacional,1,0,FINISHED
289,2025-10-25T21:30:00Z,30,SC Recife,Mirassol FC,1,2,FINISHED
228,2025-09-21T23:30:00Z,24,Santos FC,São Paulo FC,1,0,FINISHED
353,2025-11-28T22:00:00Z,36,EC Juventude,EC Bahia,1,1,FINISHED
34,2025-04-16T22:30:00Z,4,SC Corinthians Paulista,Fluminense FC,0,2,FINISHED
304,2025-11-02T21:30:00Z,31,SC Internacional,CA Mineiro,0,0,FINISHED
90,2025-05-24T21:30:00Z,10,Fluminense FC,CR Vasco da Gama,2,1,FINISHED
368,2025-12-04T00:30:00Z,37,CR Flamengo,Ceará SC,1,0,FINISHED
112,2025-06-12T22:30:00Z,12,Fortaleza EC,Santos FC,2,3,FINISHED
199,2025-08-30T19:00:00Z,22,Ceará SC,EC Juventude,0,1,FINISHED

In [171]:
# Ultimas linhas
df_brasileirao_2025.tail()

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status
375,2025-12-07T19:00:00Z,38,CA Mineiro,CR Vasco da Gama,5,0,FINISHED
376,2025-12-07T19:00:00Z,38,SC Internacional,RB Bragantino,3,1,FINISHED
377,2025-12-07T19:00:00Z,38,EC Vitória,São Paulo FC,1,0,FINISHED
378,2025-12-07T19:00:00Z,38,Ceará SC,SE Palmeiras,1,3,FINISHED
379,2025-12-07T19:00:00Z,38,SC Recife,Grêmio FBPA,0,4,FINISHED

In [172]:
df_brasileirao_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   data            380 non-null    object
 1   rodada          380 non-null    int64
 2   mandante        380 non-null    object
 3   visitante       380 non-null    object
 4   gols_mandante   380 non-null    int64
 5   gols_visitante  380 non-null    int64
 6   status          380 non-null    object
dtypes: int64(3), object(4)
memory usage: 20.9+ KB

In [173]:
print("\nVerificando valores ausentes:\n")
print(df_brasileirao_2025.isnull().sum())

Verificando valores ausentes:

data              0
rodada            0
mandante          0
visitante         0
gols_mandante     0
gols_visitante    0
status            0
dtype: int64

## 4. Pré-processamento e Engenharia de Atributos

### 4.1. Conversão de Tipos e Extração de Informações Temporais
A coluna `data` será convertida para o tipo datetime para permitir a extração de informações como mês e dia da semana, que podem ser úteis para identificar padrões.

In [174]:
# Convertendo coluna 'data' para datetime
df_brasileirao_2025['data']= pd.to_datetime(df_brasileirao_2025['data'])

In [175]:
# Criar a condição booleana para verificar a existencia de jogos não finalizados
condicao_nao_finalizados = df_brasileirao_2025['status'] != "FINISHED"
print(f"Quantidade de jogos não finalizados: {condicao_nao_finalizados.sum()} ")

Quantidade de jogos não finalizados: 0

In [176]:
# Difinir nome do time a ser trabalhado

time = 'SE Palmeiras'

# Criar condição

condicao_palmeiras = (
    (df_brasileirao_2025['mandante'] == time) |
    (df_brasileirao_2025['visitante'] == time)
    )

# Filtrar dados da SE Palmeiras e criar uma copia do DataFrame

df_palmeiras = df_brasileirao_2025[condicao_palmeiras].copy()

# Mostrando primeiras linhas do DataFrame
df_palmeiras.head()

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status
6,2025-03-30 19:00:00+00:00,1,SE Palmeiras,Botafogo FR,0,0,FINISHED
18,2025-04-06 21:30:00+00:00,2,SC Recife,SE Palmeiras,1,2,FINISHED
22,2025-04-12 21:30:00+00:00,3,SE Palmeiras,SC Corinthians Paulista,2,0,FINISHED
35,2025-04-16 22:30:00+00:00,4,SC Internacional,SE Palmeiras,0,1,FINISHED
47,2025-04-20 21:30:00+00:00,5,Fortaleza EC,SE Palmeiras,1,2,FINISHED

### 4.2. Identificação do Local do Jogo e Resultados
Criação de colunas para identificar se o jogo foi em casa ou fora, e para determinar o resultado da partida (Vitória, Empate, Derrota) do ponto de vista do Palmeiras.

In [177]:
# Criar coluna 'local_jogo'
df_palmeiras['local_jogo'] = df_palmeiras['mandante'].apply(lambda x: 'Casa' if x == 'SE Palmeiras' else 'Fora')

# Validação

print("Total de jogos:", df_palmeiras.shape[0])
print(df_palmeiras['local_jogo'].value_counts())

Total de jogos: 38
local_jogo
Casa    19
Fora    19
Name: count, dtype: int64

In [178]:
df_palmeiras.head()

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status,local_jogo
6,2025-03-30 19:00:00+00:00,1,SE Palmeiras,Botafogo FR,0,0,FINISHED,Casa
18,2025-04-06 21:30:00+00:00,2,SC Recife,SE Palmeiras,1,2,FINISHED,Fora
22,2025-04-12 21:30:00+00:00,3,SE Palmeiras,SC Corinthians Paulista,2,0,FINISHED,Casa
35,2025-04-16 22:30:00+00:00,4,SC Internacional,SE Palmeiras,0,1,FINISHED,Fora
47,2025-04-20 21:30:00+00:00,5,Fortaleza EC,SE Palmeiras,1,2,FINISHED,Fora

### 4.3. Cálculo de Gols e Pontos
Cálculo dos gols marcados e sofridos pelo Palmeiras em cada partida, e a pontuação obtida (3 para vitória, 1 para empate, 0 para derrota).

In [179]:
# Gols Pró e Gols Contra Ajustados
# Criar coluna 'gols_pro'
df_palmeiras['gols_pro'] = np.where(df_palmeiras['local_jogo'] == 'Casa', df_palmeiras['gols_mandante'], df_palmeiras['gols_visitante'])

# Criar coluna 'gols_contra'
df_palmeiras['gols_contra'] = np.where(df_palmeiras['local_jogo'] == 'Fora', df_palmeiras['gols_mandante'], df_palmeiras['gols_visitante'])

In [180]:
# Criando coluna para resultado final do jogo
conditions = [
    df_palmeiras['gols_pro'] > df_palmeiras['gols_contra'],
    df_palmeiras['gols_pro'] == df_palmeiras['gols_contra']
]
choices = ["Vitoria", "Empate"]
df_palmeiras['resultado'] = np.select(conditions, choices, default="Derrota")

In [181]:
# Criando coluna para pontos conquistados por partida
condicoes = [
    df_palmeiras['resultado'] == 'Vitoria',
    df_palmeiras['resultado'] == 'Empate'
]
pontuacao =  [3, 1]
df_palmeiras['pontos'] = np.select(condicoes, pontuacao, default = 0)

In [182]:
# Criando coluna de saldo de gols

df_palmeiras ['saldo_de_gols'] = df_palmeiras['gols_pro'] - df_palmeiras['gols_contra']

## 5. Análise Exploratória de Dados (EDA)

### 5.1. Visão Geral do Desempenho do Palmeiras
Primeiras linhas do dataset filtrado e estatísticas descritivas para o Palmeiras.

In [183]:
df_palmeiras.head()

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status,local_jogo,gols_pro,gols_contra,resultado,pontos,saldo_de_gols
6,2025-03-30 19:00:00+00:00,1,SE Palmeiras,Botafogo FR,0,0,FINISHED,Casa,0,0,Empate,1,0
18,2025-04-06 21:30:00+00:00,2,SC Recife,SE Palmeiras,1,2,FINISHED,Fora,2,1,Vitoria,3,1
22,2025-04-12 21:30:00+00:00,3,SE Palmeiras,SC Corinthians Paulista,2,0,FINISHED,Casa,2,0,Vitoria,3,2
35,2025-04-16 22:30:00+00:00,4,SC Internacional,SE Palmeiras,0,1,FINISHED,Fora,1,0,Vitoria,3,1
47,2025-04-20 21:30:00+00:00,5,Fortaleza EC,SE Palmeiras,1,2,FINISHED,Fora,2,1,Vitoria,3,1

In [184]:
df_palmeiras.tail()

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status,local_jogo,gols_pro,gols_contra,resultado,pontos,saldo_de_gols
332,2025-11-19 22:30:00+00:00,37,SE Palmeiras,EC Vitória,0,0,FINISHED,Casa,0,0,Empate,1,0
342,2025-11-23 00:30:00+00:00,35,SE Palmeiras,Fluminense FC,0,0,FINISHED,Casa,0,0,Empate,1,0
350,2025-11-26 00:30:00+00:00,36,Grêmio FBPA,SE Palmeiras,3,2,FINISHED,Fora,2,3,Derrota,0,-1
367,2025-12-04 00:30:00+00:00,34,CA Mineiro,SE Palmeiras,0,3,FINISHED,Fora,3,0,Vitoria,3,3
378,2025-12-07 19:00:00+00:00,38,Ceará SC,SE Palmeiras,1,3,FINISHED,Fora,3,1,Vitoria,3,2

In [185]:
df_palmeiras.sample(10)

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status,local_jogo,gols_pro,gols_contra,resultado,pontos,saldo_de_gols
223,2025-09-21 00:00:00+00:00,24,SE Palmeiras,Fortaleza EC,4,1,FINISHED,Casa,4,1,Vitoria,3,3
151,2025-07-27 00:00:00+00:00,17,SE Palmeiras,Grêmio FBPA,1,0,FINISHED,Casa,1,0,Vitoria,3,1
211,2025-09-13 21:30:00+00:00,23,SE Palmeiras,SC Internacional,4,1,FINISHED,Casa,4,1,Vitoria,3,3
378,2025-12-07 19:00:00+00:00,38,Ceará SC,SE Palmeiras,1,3,FINISHED,Fora,3,1,Vitoria,3,2
295,2025-10-26 23:30:00+00:00,30,SE Palmeiras,Cruzeiro EC,0,0,FINISHED,Casa,0,0,Empate,1,0
332,2025-11-19 22:30:00+00:00,37,SE Palmeiras,EC Vitória,0,0,FINISHED,Casa,0,0,Empate,1,0
6,2025-03-30 19:00:00+00:00,1,SE Palmeiras,Botafogo FR,0,0,FINISHED,Casa,0,0,Empate,1,0
257,2025-10-05 19:00:00+00:00,27,São Paulo FC,SE Palmeiras,2,3,FINISHED,Fora,3,2,Vitoria,3,1
65,2025-05-04 19:00:00+00:00,7,CR Vasco da Gama,SE Palmeiras,0,1,FINISHED,Fora,1,0,Vitoria,3,1
107,2025-06-01 22:30:00+00:00,11,Cruzeiro EC,SE Palmeiras,2,1,FINISHED,Fora,1,2,Derrota,0,-1

### 5.2. Análise de Resultados (Vitórias, Empates, Derrotas)
Contagem e visualização dos resultados das partidas do Palmeiras.

In [186]:
# Totais Gerais
total_vitorias = df_palmeiras['resultado'].value_counts().get('Vitoria', 0)
total_empates = df_palmeiras['resultado'].value_counts().get('Empate', 0)
total_derrotas = df_palmeiras['resultado'].value_counts().get('Derrota', 0)
total_pontos = df_palmeiras['pontos'].sum()
total_gols_pro = df_palmeiras['gols_pro'].sum()
total_gols_contra = df_palmeiras['gols_contra'].sum()
saldo_de_gol = total_gols_pro - total_gols_contra

print(f"Total de Vitórias: {total_vitorias}")
print(f"Total de Empates: {total_empates}")
print(f"Total de Derrotas: {total_derrotas}")
print(f"Total de Pontos: {total_pontos}")
print(f"Total de Gols a Favor: {total_gols_pro}")
print(f"Total de Gols Contra: {total_gols_contra}")
print(f"Saldo de Gols: {saldo_de_gol}")

Total de Vitórias: 23
Total de Empates: 7
Total de Derrotas: 8
Total de Pontos: 76
Total de Gols a Favor: 66
Total de Gols Contra: 33
Saldo de Gols: 33

In [187]:
# Calculo de numero de jogos ou numero de rodadas no campeonato
numero_jogos = df_palmeiras.shape[0]

# Calculo de pontos maximos que um time pode fazer
pontos_maximos = numero_jogos * 3

# Calculo de pontos perdidos pelo o palmeiras
pontos_perdidos = pontos_maximos - total_pontos

# Imprime os resultados
print(f"Número de rodadas: {numero_jogos}")
print(f"Total de pontos máximos possiveis no campeonato: {pontos_maximos}")
print(f"Total de pontos conquistados pelo Palmeiras no Campeonato Brasileiro de 2025: {total_pontos}")
print(f"Pontos perdidos pelo Palmeiras no Campeonato Brasileiro de 2025: {pontos_perdidos}")

Número de rodadas: 38
Total de pontos máximos possiveis no campeonato: 114
Total de pontos conquistados pelo Palmeiras no Campeonato Brasileiro de 2025: 76
Pontos perdidos pelo Palmeiras no Campeonato Brasileiro de 2025: 38

### 5.3. Desempenho em Casa vs. Fora
Comparação da performance do Palmeiras quando joga como mandante e como visitante.

In [188]:
# Desempenho Casa x Fora
resumo_casa_fora = (
    df_palmeiras
        .groupby('local_jogo')
        .agg(
            pontos_total=('pontos', 'sum'),
            gols_pro_total=('gols_pro', 'sum'),
            gols_contra_total=('gols_contra', 'sum'),
            vitorias=('resultado', lambda x: (x == 'Vitoria').sum()),
            empates=('resultado', lambda x: (x == 'Empate').sum()),
            derrotas=('resultado', lambda x: (x == 'Derrota').sum())
        )
        .reset_index()
)

resumo_casa_fora

,local_jogo,pontos_total,gols_pro_total,gols_contra_total,vitorias,empates,derrotas
0,Casa,41,35,11,12,5,2
1,Fora,35,31,22,11,2,6

In [189]:
# Métricas percentuais

# Aproveitamento de pontos
aproveitamento_percentual = total_pontos / pontos_maximos * 100

# Média de gols feitos
media_gols_pro = total_gols_pro / numero_jogos

# Média gols contra
media_gols_contra = total_gols_contra / numero_jogos

print(f"Percentual de pontos conquistados: {aproveitamento_percentual:.2f}%")
print(f"Média de gols feitos por jogo: {media_gols_pro:.2f}")
print(f"Média de gols sofridos por jogo: {media_gols_contra:.2f}")

Percentual de pontos conquistados: 66.67%
Média de gols feitos por jogo: 1.74
Média de gols sofridos por jogo: 0.87

## 6. Análise de Vítimas e Carrascos

### 6.1. Maiores Vítimas do Palmeiras
Identificação dos times que o Palmeiras mais venceu no Campeonato Brasileiro de 2025.

In [190]:
# Identificando as vítimas (times que o Palmeiras mais venceu)
vitorias_mandante = df_palmeiras[(df_palmeiras['mandante'] == time) & (df_palmeiras['resultado'] == 'Vitoria')]['visitante'].value_counts()
vitorias_visitante = df_palmeiras[(df_palmeiras['visitante'] == time) & (df_palmeiras['resultado'] == 'Vitoria')]['mandante'].value_counts()

maiores_vitimas = (vitorias_mandante.add(vitorias_visitante, fill_value=0)).sort_values(ascending=False)
print("Maiores Vítimas do Palmeiras:")
print(maiores_vitimas.head())

Maiores Vítimas do Palmeiras:
CA Mineiro          2.0
CR Vasco da Gama    2.0
EC Juventude        2.0
Ceará SC            2.0
RB Bragantino       2.0
Name: count, dtype: float64

### 6.2. Maiores Carrascos do Palmeiras
Identificação dos times que mais venceram o Palmeiras no Campeonato Brasileiro de 2025.

In [191]:
# Identificando os carrascos (times que mais venceram o Palmeiras)
derrotas_mandante = df_palmeiras[(df_palmeiras['mandante'] == time) & (df_palmeiras['resultado'] == 'Derrota')]['visitante'].value_counts()
derrotas_visitante = df_palmeiras[(df_palmeiras['visitante'] == time) & (df_palmeiras['resultado'] == 'Derrota')]['mandante'].value_counts()

maiores_carrascos = (derrotas_mandante.add(derrotas_visitante, fill_value=0)).sort_values(ascending=False)
print("""
Maiores Carrascos do Palmeiras:
""")
print(maiores_carrascos.head())

Maiores Carrascos do Palmeiras:

CR Flamengo    2.0
EC Bahia       2.0
Cruzeiro EC    1.0
Grêmio FBPA    1.0
Mirassol FC    1.0
Name: count, dtype: float64

## 7. Preparação para Power BI

Para facilitar a criação de visualizações interativas no Power BI, o DataFrame `df_palmeiras` será exportado para um arquivo CSV. Este arquivo conterá todas as colunas processadas e as métricas de desempenho do Palmeiras, prontas para serem carregadas na ferramenta de BI.

### 7.1. Refinamento dos dados para exportação

In [192]:
# Ordenação por data

df_palmeiras = df_palmeiras.sort_values('data')

In [193]:
# Resetar índice

df_palmeiras.reset_index(drop=True, inplace=True)

In [194]:
df_palmeiras.head(10)

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status,local_jogo,gols_pro,gols_contra,resultado,pontos,saldo_de_gols
0,2025-03-30 19:00:00+00:00,1,SE Palmeiras,Botafogo FR,0,0,FINISHED,Casa,0,0,Empate,1,0
1,2025-04-06 21:30:00+00:00,2,SC Recife,SE Palmeiras,1,2,FINISHED,Fora,2,1,Vitoria,3,1
2,2025-04-12 21:30:00+00:00,3,SE Palmeiras,SC Corinthians Paulista,2,0,FINISHED,Casa,2,0,Vitoria,3,2
3,2025-04-16 22:30:00+00:00,4,SC Internacional,SE Palmeiras,0,1,FINISHED,Fora,1,0,Vitoria,3,1
4,2025-04-20 21:30:00+00:00,5,Fortaleza EC,SE Palmeiras,1,2,FINISHED,Fora,2,1,Vitoria,3,1
5,2025-04-27 21:30:00+00:00,6,SE Palmeiras,EC Bahia,0,1,FINISHED,Casa,0,1,Derrota,0,-1
6,2025-05-04 19:00:00+00:00,7,CR Vasco da Gama,SE Palmeiras,0,1,FINISHED,Fora,1,0,Vitoria,3,1
7,2025-05-11 20:30:00+00:00,8,SE Palmeiras,São Paulo FC,1,0,FINISHED,Casa,1,0,Vitoria,3,1
8,2025-05-18 21:30:00+00:00,9,RB Bragantino,SE Palmeiras,1,2,FINISHED,Fora,2,1,Vitoria,3,1
9,2025-05-25 19:00:00+00:00,10,SE Palmeiras,CR Flamengo,0,2,FINISHED,Casa,0,2,Derrota,0,-2

### 7.2. Exportação do DataFrame

In [195]:
# Exportar o DataFrame processado para CSV
df_palmeiras.to_csv("palmeiras_jogos_2025.csv", index=False)

resumo_casa_fora.to_csv("palmeiras_casa_fora_2025.csv", index=False)